### ISSUE TITLE
completion of aliases in zsh

### ISSUE THREAD

**Issue by Konfekt** [sigoden/argc-completions#17]
In ZSH built-in completion is transferred to aliases, say `alias sc=systemctl` would allow you to complete `sc` like `systemctl`.  Just following the set-up instructions with argc-completions  I could not achieve the same. How would that go?

**Comment by sigoden** [comment]
Aliases completion is ok. The pre-processing of aliases is done by zsh itself. Argc-completions is equivalent to adding over 1000 completion scripts. In addition, it will have no impact on the shell. @Konfekt

```
alias sc=systemctl
```
![image](https://github.com/sigoden/argc-completions/assets/4012553/d39887cc-2cec-46a1-b7fb-cc9013626a4f)
```
alias sctl=systemctl
```
![image](https://github.com/sigoden/argc-completions/assets/4012553/5b3b165d-bbaf-4fd7-a012-85ed3aacbeab)

**Comment by Konfekt** [comment]
Thank you, for some reason it is working now after changing the load order
