### ISSUE TITLE
Clear completion list (ZSH)

### ISSUE THREAD

**Issue by baudneo** [sigoden/argc-completions#31]
### Describe the bug

Is there a mechanism to clear the completion list? Something like hitting \<ESC\> to clear it?

Example:

```bash
╰─❯ argc check rrr
check      -- Check the completion script
check:all  -- Check all completion scripts
```

After typing r, the completions do not clear until I hit \<TAB\> or \<RETURN\>. It would be great if I were able to hit \<ESC\> or something to clear the completion list.

### How to reproduce

See example above

### Expected behavior

I am hoping that there is a mechanism to clear the completion list from the screen.

### Shell

zsh 5.8 (x86_64-debian-linux-gnu)

### Version

argc-completions 2ff10cf
argc 1.14.0
yq (https://github.com/mikefarah/yq/) version v4.40.3
GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)
sed (GNU sed) 4.7
Linux pve740 5.15.131-1-pve #1 SMP PVE 5.15.131-2 (2023-11-14T11:32Z) x86_64 GNU/Linux

**Comment by sigoden** [comment]
This is a matter of zsh. You can study how to configure zsh to meet your needs.

argc completions just provides completion scripts.
