### ISSUE TITLE
Generating fio command throws an error

### ISSUE THREAD

**Issue by baudneo** [sigoden/argc-completions#36]
### Describe the bug

No completions for fio OOB, tried to run the `argc generate fio` command and it errros out.

```
❯ argc generate fio
Generate fio
[error] @option(line 18) has '--enghelp' already exists at line 17
```

# completions/fio.sh
```
################# only showing line 17 & 18
# @option --enghelp <engine>        Print ioengine help, or list available ioengines
# @option --enghelp <engine,cmd>    Print help for an ioengine cmd
```

### How to reproduce

cd into the argc-completions repo folder and run `argc generate fio`

### Expected behavior

generate and use completions

### Shell

zsh 5.9 (x86_64-pc-linux-gnu)

### Version

argc 1.12.1
yq (https://github.com/mikefarah/yq/) version v4.40.2
GNU Awk 5.3.0, API 4.0, PMA Avon 8-g1, (GNU MPFR 4.2.1, GNU MP 6.3.0)
sed (GNU sed) 4.9

**Comment by sigoden** [comment]
This is not uncommon. In this case, you need to create src/fio.sh to intervene in the generation.

Try it, use `_patch_table_dedup_options`

**Comment by baudneo** [comment]
Thanks! I haven't had time to really drill down so the tip really helps!
