### ISSUE TITLE
pnpm run adds quotes in fish shell

### ISSUE THREAD

**Issue by drmikecrowe** [sigoden/argc-completions#39]
Any idea why this would be happening?

![image](https://github.com/sigoden/argc-completions/assets/90312/a13b70ba-807f-4bd0-9d69-8c1d5fc3ace8)

I've been trying to port it to NixOS, and it's working great for other commands.  My setup is:

```sh
show_media_bias  main @ 729bc98 ⩮✘∽⋄ ❄️ devenv-shell❯  cat (argc-completions-folder)/argc.fish
set -gx ARGC_COMPLETIONS_ROOT "/nix/store/z1kppvmc48kv1aghrz7p945mnf158cqq-argc-completions-2023-12-29"
set -gx ARGC_COMPLETIONS_PATH "$ARGC_COMPLETIONS_ROOT/completions"
fish_add_path "$ARGC_COMPLETIONS_ROOT/bin"
# To add a subset of completions only, change next line e.g. set argc_scripts cargo git
set argc_scripts (ls -1 "$ARGC_COMPLETIONS_ROOT/completions" | sed -n 's/\.sh$//p')
argc --argc-completions fish $argc_scripts | source

show_media_bias  main @ 729bc98 ⩮✘∽⋄ ❄️ devenv-shell❯  argc --argc-completions fish pnpm
function _argc_completer
    set -l args (commandline -o)
    set -l cur (commandline -t)
    if [ ! "$cur" ]
        set -a args ''
    end

    argc --argc-compgen fish "" $args
end


for cmd in argc pnpm
    complete -x -k -c $cmd -a "(_argc_completer)"
end
```

**Comment by sigoden** [comment]
Cann't reproduce the issue.

![image](https://github.com/sigoden/argc-completions/assets/4012553/cc47305e-6858-40b0-84e9-a8d68e729e03)
![image](https://github.com/sigoden/argc-completions/assets/4012553/d9991bb9-61a5-4702-86f3-eb1446b38b0d)
![image](https://github.com/sigoden/argc-completions/assets/4012553/c1035b28-9f03-4201-825e-6cc599ab96e9)

I don't think there is a problem with the current argc-completions.

**Comment by drmikecrowe** [comment]
You have -- sorry I wasn't clear:  The `\` in your first example is the issue:

![argc-issue-2024-02-05 18-11](https://github.com/sigoden/argc-completions/assets/90312/513afeba-abd6-4244-9ed6-3b4d52717dd7)

**Comment by sigoden** [comment]
The fish built-in completer will not complete anything when triggered by `\"`.

![argc-completions](https://github.com/sigoden/argc-completions/assets/4012553/0d17a369-48dc-4fc5-b45d-c33ed244c9c2)
