### ISSUE TITLE
Help with nushell completions

### ISSUE THREAD

**Issue by drmikecrowe** [sigoden/argc-completions#41]
Thanks for helping me with my yq issues.  I'm now seeing this when I activate with nushell:

```log
show_media_bias  main @ 729bc98 ⩮✘∽⋄⇣ ❄️ devenv-shell❯ pnpm run Error:   × Automatically spreading lists is deprecated
```

I _think_ it wants the code to be:

```nu
def _argc_completer [args: list<string>] {
    argc --argc-compgen nushell "" ...$args
...
```

However, when I make this change, I'm getting a leading `| ` in my completion.  Is this not the right fix?

![image](https://github.com/sigoden/argc-completions/assets/90312/3bd21b36-8b08-4a55-98be-4c0321f3a6c3)

My complete script is:

```nu
def _argc_completer [args: list<string>] {
    argc --argc-compgen nushell "" ...$args
        | split row "\n" | range 0..-2 
        | each { |line| $line | split column "\t" value description } | flatten 
}

let external_completer = {|spans| 
    _argc_completer $spans
}

$env.config.completions.external.enable = true
$env.config.completions.external.completer = $external_completer
```

Here's how it happens:

![argc-issue-2](https://github.com/sigoden/argc-completions/assets/90312/b0179c8c-5d57-4e15-973b-d81d0fd5debe)

**Comment by sigoden** [comment]
sigoden/argc#285 fixed nushell completion script.

In nushell, the leading indicator is dynamic, `|` for completion menu, `?` for history/help menu.
https://github.com/nushell/nushell/blob/e7f1bf85350b4c2cf3e89ef39434b73c381730c8/crates/nu-cli/src/reedline_config.rs#L23

![argc-completions2](https://github.com/sigoden/argc-completions/assets/4012553/f13a222a-c0fd-4ec2-85bf-4c17d08248d7)
