### ISSUE TITLE
nushell: slow?

### ISSUE THREAD

**Issue by rutexd** [sigoden/argc-completions#49]
Looks like its pretty slow on nushell... About 1-2 sec delay between after i press tab and results are in.

is it intended to be slow like this? 

[WindowsTerminal_3O37PCBT4y.webm](https://github.com/sigoden/argc-completions/assets/112971914/07829905-c000-42ce-8833-ae66109acee6)

**Comment by sigoden** [comment]
Argc-completions dynamically completes everything.The completer invokes argc command to generate completion candidates.

Additionally, invoking commands on Windows is noticeably slower than on Unix-like systems, so latency can be felt.
