### ISSUE TITLE
Add this repo as a Homebrew Formulae

### ISSUE THREAD

**Issue by danemacmillan** [sigoden/argc-completions#54]
In the same way that your main [`argc`](https://formulae.brew.sh/formula/argc) utility is part of brew, it would be handy to package up this repo so a simple `brew install argc-completions` would do the work of installing its dependencies and adding a few lines to someone's rc file. This would go a long way towards simplifying users' environment building automations they may have.

Thanks for this repo!

**Comment by sigoden** [comment]
Not now.
