### ISSUE TITLE
fzf-tab integration

### ISSUE THREAD

**Issue by kqvanity** [sigoden/argc-completions#61]
I use [fzf-tab](https://github.com/Aloxaf/fzf-tab) to provide autocompletions when hitting tab key. When I source argc-completions in zsh as well, It overrides fzf-tab, showing its completion menu instead, which works for the most, but has few culprits. Like for example, now showing folder coloring, fzf-tab completion menu is completely overridden, nested file paths not showing. (just 0/X results)
![Screenshot_20241006-184801_819x117](https://github.com/user-attachments/assets/c12d808c-9edb-4a55-a0b6-7b8e1f5801d2)

Could you also provide it as a plugin for oh-my-zsh?

**Comment by sigoden** [comment]
This is beyond the scope of argc-completions; argc-completions only provides native completion for the shell.
